// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVrlxUb6yCJfyPiWMuEt3n_llJFa5N2HY',
    appId: '1:656952495666:android:75fd24a7af94e76db5f62b',
    messagingSenderId: '656952495666',
    projectId: 'iothnicapp',
    databaseURL: 'https://iothnicapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iothnicapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVXDt2tqdKPToqc5Qs2Zj6vNiCvo_yNM0',
    appId: '1:656952495666:ios:df1ccbd6985e3d83b5f62b',
    messagingSenderId: '656952495666',
    projectId: 'iothnicapp',
    databaseURL: 'https://iothnicapp-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iothnicapp.appspot.com',
    iosClientId: '656952495666-f2od1hpg16sm9af4do3kf1gd55rl1e66.apps.googleusercontent.com',
    iosBundleId: 'com.example.iothnicapp',
  );
}
